---
- name: Perform Syncthing installation tasks
  when: syncthing_enabled | bool
  tags:
    - setup-all
    - setup-syncthing
    - install-all
    - install-syncthing
  block:
    # - name: Gather and set facts for Syncthing installation
    #   ansible.builtin.include_tasks: fact.yaml
    # - name: Install Syncthing
    #   ansible.builtin.include_tasks: install.yaml
    # - name: Configure Syncthing
    #   ansible.builtin.include_tasks: config.yaml
    - name: uninstall Syncthing
      ansible.builtin.include_tasks: uninstall.yaml

  
- name: Perform Syncthing uninstallation tasks
  when: not syncthing_enabled | bool
  tags:
    - setup-all
    - setup-syncthing
  block:
    - name: Uninstall Syncthing
      ansible.builtin.include_tasks: uninstall.yaml
